<?php

namespace Database\Seeders;

use App\Models\Schedules;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class ScheduleTableSeeder extends Seeder
{
    public function run(): void
    {

        DB::table('schedules')->insert([
            [
                'id' => 1,
                'schedule_type' => 'enroll',
                'lab_id' => 1,
                'course_id' => 2,
                'booking_id' => null,
                'day_of_week' => 'Monday',
                'date' => '2026-06-15',
                'is_recurring' => 1,
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'created_at' => '2026-06-26 21:25:02',
                'updated_at' => '2026-06-26 21:25:02',
                'semester_id' => 1,
            ],
            [
                'id' => 2,
                'schedule_type' => 'enroll',
                'lab_id' => 1,
                'course_id' => 4,
                'booking_id' => null,
                'day_of_week' => 'Monday',
                'date' => '2026-06-22',
                'is_recurring' => 1,
                'start_time' => '11:00:00',
                'end_time' => '13:00:00',
                'created_at' => '2026-06-26 21:25:30',
                'updated_at' => '2026-06-26 21:25:30',
                'semester_id' => 1,
            ],
            [
                'id' => 3,
                'schedule_type' => 'enroll',
                'lab_id' => 1,
                'course_id' => 7,
                'booking_id' => null,
                'day_of_week' => 'Tuesday',
                'date' => '2026-06-23',
                'is_recurring' => 1,
                'start_time' => '09:00:00',
                'end_time' => '10:00:00',
                'created_at' => '2026-06-26 21:25:47',
                'updated_at' => '2026-06-26 21:25:47',
                'semester_id' => 1,
            ],
            [
                'id' => 4,
                'schedule_type' => 'enroll',
                'lab_id' => 1,
                'course_id' => 1,
                'booking_id' => null,
                'day_of_week' => 'Wednesday',
                'date' => '2026-06-24',
                'is_recurring' => 1,
                'start_time' => '15:00:00',
                'end_time' => '18:00:00',
                'created_at' => '2026-06-26 21:26:34',
                'updated_at' => '2026-06-26 21:26:42',
                'semester_id' => 1,
            ],
            [
                'id' => 5,
                'schedule_type' => 'enroll',
                'lab_id' => 1,
                'course_id' => 6,
                'booking_id' => null,
                'day_of_week' => 'Wednesday',
                'date' => '2026-06-24',
                'is_recurring' => 1,
                'start_time' => '09:00:00',
                'end_time' => '11:00:00',
                'created_at' => '2026-06-26 21:27:46',
                'updated_at' => '2026-06-26 21:27:46',
                'semester_id' => 1,
            ],
            [
                'id' => 6,
                'schedule_type' => 'enroll',
                'lab_id' => 1,
                'course_id' => 5,
                'booking_id' => null,
                'day_of_week' => 'Thursday',
                'date' => '2026-06-25',
                'is_recurring' => 1,
                'start_time' => '12:00:00',
                'end_time' => '14:00:00',
                'created_at' => '2026-06-26 21:29:14',
                'updated_at' => '2026-06-26 21:38:30',
                'semester_id' => 1,
            ],
            [
                'id' => 7,
                'schedule_type' => 'booking',
                'lab_id' => 1,
                'course_id' => null,
                'booking_id' => 1,
                'day_of_week' => 'Monday',
                'date' => '2026-06-29',
                'is_recurring' => 0,
                'start_time' => '14:00:00',
                'end_time' => '18:00:00',
                'created_at' => '2026-06-26 21:30:34',
                'updated_at' => '2026-06-26 21:30:34',
                'semester_id' => 1,
            ],
            [
                'id' => 8,
                'schedule_type' => 'maintenance',
                'lab_id' => 1,
                'course_id' => null,
                'booking_id' => 2,
                'day_of_week' => 'Friday',
                'date' => '2026-07-03',
                'is_recurring' => 0,
                'start_time' => '08:00:00',
                'end_time' => '18:00:00',
                'created_at' => '2026-06-26 21:31:11',
                'updated_at' => '2026-06-26 21:31:45',
                'semester_id' => null,
            ],
            [
                'id' => 9,
                'schedule_type' => 'booking',
                'lab_id' => 1,
                'course_id' => null,
                'booking_id' => 3,
                'day_of_week' => 'Tuesday',
                'date' => '2026-06-30',
                'is_recurring' => 0,
                'start_time' => '12:00:00',
                'end_time' => '18:00:00',
                'created_at' => '2026-06-26 21:34:18',
                'updated_at' => '2026-06-26 21:34:28',
                'semester_id' => 1,
            ],
            [
                'id' => 10,
                'schedule_type' => 'maintenance',
                'lab_id' => 1,
                'course_id' => null,
                'booking_id' => 4,
                'day_of_week' => 'Thursday',
                'date' => '2026-07-02',
                'is_recurring' => 0,
                'start_time' => '14:00:00',
                'end_time' => '18:00:00',
                'created_at' => '2026-06-26 21:35:49',
                'updated_at' => '2026-06-26 21:36:02',
                'semester_id' => null,
            ],
            [
                'id' => 11,
                'schedule_type' => 'enroll',
                'lab_id' => 2,
                'course_id' => 2,
                'booking_id' => null,
                'day_of_week' => 'Tuesday',
                'date' => '2026-06-23',
                'is_recurring' => 1,
                'start_time' => '12:00:00',
                'end_time' => '14:00:00',
                'created_at' => '2026-06-26 21:37:36',
                'updated_at' => '2026-06-26 21:37:36',
                'semester_id' => 1,
            ],
            [
                'id' => 12,
                'schedule_type' => 'enroll',
                'lab_id' => 2,
                'course_id' => 4,
                'booking_id' => null,
                'day_of_week' => 'Thursday',
                'date' => '2026-06-25',
                'is_recurring' => 1,
                'start_time' => '15:00:00',
                'end_time' => '17:00:00',
                'created_at' => '2026-06-26 21:37:58',
                'updated_at' => '2026-06-26 21:37:58',
                'semester_id' => 1,
            ],
            [
                'id' => 13,
                'schedule_type' => 'enroll',
                'lab_id' => 2,
                'course_id' => 1,
                'booking_id' => null,
                'day_of_week' => 'Tuesday',
                'date' => '2026-06-23',
                'is_recurring' => 1,
                'start_time' => '15:00:00',
                'end_time' => '18:00:00',
                'created_at' => '2026-06-26 21:39:58',
                'updated_at' => '2026-06-26 21:40:05',
                'semester_id' => 1,
            ],
        ]);
    }
}
